### ISSUE TITLE
[bug] exact region name may return fuzzy named super group

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#103]
as of v0.3a2

min repro:

```python
import siibra
atlas=siibra.atlases['rat']
parc=atlas.parcellations['v4']
region_name='lateral olfactory tract'
parc.decode_region(region_name)
```

expected result:
returns exact match region with name `lateral olfactory tract`

actual result:
returns fuzzy matched super group

```
Group: Nucleus of the lateral olfactory tract,Olfactory white matter
├── Nucleus of the lateral olfactory tract
└── Olfactory white matter
    └── lateral olfactory tract
```

**Comment by dickscheid** [comment]
That's a very interesting case, since the search term  matches exactly the tract but also with full length the nucleus. We have to catch the case of a truly exact match, then not build groups.

The deeper question is wether we need some form of scoring fuzzy matches for other corner cases, but this is far from trivial.

**Comment by xgui3783** [comment]
check `decode_region` vs `find_region`
