### ISSUE TITLE
Return ng-precomputed URLs for MNI template spaces as well

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-python#12]
siibra-explorer also reads the MRI-scale data from precomputed URLs. These URLs need to be included in the parcellations definition, and forwarded.

**Comment by xgui3783** [comment]
would you like me to comment them here, or push them in a json file in a branch? @dickscheid @marcenko

**Comment by xgui3783** [comment]
I have tentatively extracted the precomputed url into JSON files, and attach them here. 

several caveats:
- precomputed url's in neuroglancer parlance always start with `precomputed://` . I opted to leave them in
- we can ignore any entry with `.layerName == 'auxMesh'` (incidentally, they have `precompmesh://` as their protocol, and are meshes for the template. neuroglancer does not allow meshes to be assigned to image layer, `precompmesh` is the hack we needed to do

[precomputed.zip](https://github.com/FZJ-INM1-BDA/siibra-python/files/6348460/precomputed.zip)

**Comment by xgui3783** [comment]
I have started working on a fix, and will raise a PR when ready.

**Comment by dickscheid** [comment]
We will have to revisit the solution. The precomputed URLs are in fact an alternative source URL for the data, so we should probable convert the existing template and map URLs in the configuration files to lists or dictionaries. I also want to understand the logic of putting basic precomputed metadata in the confguration file vs. pulling it from the precomputed http site, which is done in bigbrain.py

**Comment by xgui3783** [comment]
for big brain, they are similar , with the following exceptions:

- volumeSrc also provides transform for `volume_type: neuroglancer/precomputed`. 

Since there are neuroglancer volume does not have a header file like nifti, this information is vital for for viewer to position the volume in the space correctly

For MRI & MRI resolution segmentation niftis, the endpoint of precomputed chunks currently do not exist. `volumeSrc` should be able to point to both original nifti, as well as precomputed endpoint (ideally, also datalad repository on how this transformation occurred)

---

the lack of precomputed endpoint is a blocking issue in siibra-explorer. We can certainly discuss the implementation in detail in coming days, but in the mean time, to allow us to temporarily unblock this issue I propose either:

- we change attribute  name from `volume_src` to `_volume_src`, to signify that this is an experimental attribute and subject to change, OR
- we leave the pr/branch as is, and I can fork and deploy `siibra-api` to build from `feat_addVolsrc` branch.  siibra-explorer will point to the forked siibra-api and revert it to the official siibra-api once the discussion completes.

**Comment by xgui3783** [comment]
fixed by #17
