### ISSUE TITLE
[bug] area 9 receptor ebrains dataset fetched when hoc2 right is defined as roi

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#144]
siibra version: 0.3a5

min repro:

```python
import siibra
from siibra.core import Atlas, Parcellation

atlas:Atlas = siibra.atlases['human']
parc:Parcellation = atlas.parcellations['2 9']
regions = parc.find_regions('hoc2 right')
hoc2_right = regions[0]
print(hoc2_right)
features = siibra.get_features(hoc2_right, 'ebrains')
print([f.name for f in features])
```

expected return

```
[]
```

actual return 

```
['Density measurements of different receptors for Area 9 [human, v1.0]']
```

additional information:

possibly also the case for `Area hOc3d (Cuneus) left` instead of `hoc2 right`

**Comment by dickscheid** [comment]
This problem was caused by a recent update which removed words included in the parcellation name from the region specifciations for region name matching. This  mechanism also removed the "9" from the are name because it was a 'word' in Julich-Brain 2 9. With  95d83a6, only alphanumeric words with more than 2 characters are being removed, which fixes the problem.
