### ISSUE TITLE
Problem extracting gene expression data for a whole parcellation

### ISSUE THREAD

**Issue by dagush** [FZJ-INM1-BDA/siibra-python#182]
Hello,
  When I try to extract the Allen gene expression data using Siibra, when done for a whole parcellation it gives an endless string of warnings and finally returns an empty array. When done with a specific region it doesn't happen.

```
atlas = siibra.atlases['human']
julich_brain = atlas.get_parcellation("julich")
features = siibra.get_features(julich_brain, siibra.modalities.GeneExpression, gene=siibra.features.gene_names.GABARAPL2)

```
The warning is (just one example) :
```
[siibra:INFO] <class 'siibra.features.genes.GeneExpression'> matching against root node Julich-Brain Cytoarchitectonic Maps 2.9 of Julich-Brain Cytoarchitectonic Maps 2.9
[siibra:WARNING] Cannot test overlap of Point in MNI152 2009c nonl asym [-24.0,59.0,-15.0] with Julich-Brain Cytoarchitectonic Maps 2.9

```
  thanks!!!
gus.-

**Comment by dickscheid** [comment]
Thanks. I can reproduce the problem. The root cause is that when querying spatial features for a region subtree, siibra will test wether this region is fully mapped in the space where the feature is defined. The test is done recursively, so all subtrees have to be mapped. This leads to many tests when querying a complete parcellation, and ultimately to zero features if any of the regions is not mapped. We will fix the problem.

Meanwhile I suggest to collect gene expressions by iterating over the leave region nodes:

```python
import siibra
atlas = siibra.atlases['human']
julich_brain = atlas.get_parcellation("julich 2.9")
features = {}
gene = siibra.gene_names.GABARAPL2
for region in julich_brain.regiontree.leaves:
    with siibra.QUIET:
        try:
            features[region] = siibra.get_features(region, "geneexp", gene=gene)
        except:
            features[region] = []
    print(f"{len(features[region]):4} {region.name}")
```
