### ISSUE TITLE
`atlas.get_features` method should be cached

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#19]
min reproduce:

```python
import siibra as sb
atlas=sb.atlases.MULTILEVEL_HUMAN_ATLAS
atlas.select_region('hoc1 left')
connpr1=atlas.get_features(sb.modalities.ConnectivityProfile) # takes a very long time
connpr2=atlas.get_features(sb.modalities.ConnectivityProfile) # also takes a very long time
```

expected behaviour: second call should return cached result, rather than fetch result from scratch

**Comment by dickscheid** [comment]
True, this is unnecessary. Two measures taken:

1. Use class variables in receptor and connectivity feature extractors, so they retrieve only once.
2. Cache the pick_selection() method of feature extractors. This required to define a hash for atlas objects.

Fixed by 1d84104

We should see if the pattern used could not be a general pattern of the parent FeatureExtractor (didn't have time to check this).
