### ISSUE TITLE
[0.4] get functional connectivity matrix error

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#245]
commit: 3d1ceb496b8303760c3f481c5aa69d84584b051e

example code:

```python
import siibra
features = siibra.features.get(siibra.parcellations['2.9'], siibra.features.connectivity.FunctionalConnectivity)
assert len(features) > 0
feat = features[0]
feat.get_matrix(feat.subjects[0]) # error here
```

expected: returns matrix

actual: Runtimeerror

```
RuntimeError: Non-quadratic connectivity matrix 294x1 from 294-Julich-Brain/2FunctionalConnectivity/000/EmpCorrFC_concatenated.csv in ZipfileConnector: /home/xgui3783/.cache/siibra.retrieval/c5f0e85a1fc2657c64df393663e0dccc9c7da65fdfbc8d2ced6a5a181712b46e
```

**Comment by AhmetNSimsek** [comment]
The issue is caused by the format of the data. The array comes in `nrows` with 1 column where each cell is a `str`. These strings are `nrow` many floats joined together with a space. I wrote a fix for when a subject is selected, however, when the mean is requested it still fails as it does not go through `_load_matrix` method. Currently, considering other possible fixes.

**Comment by xgui3783** [comment]
This was actually the solution I was thinking about last night.
