### ISSUE TITLE
[0.5][enh] use threadpool for network bound tasks 

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#250]
some network bound tasks takes unreasonably long to complete. e.g.

```python
import siibra
with siibra.QUIET:  # suppress progress output
    hcp_maps = siibra.get_map(
        space="mni152", parcellation=siibra.parcellations.SHORT_FIBER_BUNDLES_HCP, maptype="statistical"
    )
pmap = next(iter(hcp_maps))
```

took 8 minutes to complete:

```
Fetching 673 volumetric maps: 100%|██████████| 673/673 [08:17<00:00,  1.35maps/s]
```

**Comment by AhmetNSimsek** [comment]
The time is spent in building the `SparseIndex`. https://github.com/FZJ-INM1-BDA/siibra-python/issues/334 aims to solve this for preconfigured maps. However, this remains an issue when the data is unreachable (due to network etc) and user data.

To use a threadpool to calculate the `SparseIndex`, `add_img` may require rework to be run in parallel.

**Comment by AhmetNSimsek** [comment]
As of 43e4b80296d74dd34d5b23385d7bd5e131b5096c, this is much faster: less than 30 seconds.
