### ISSUE TITLE
[0.4] fetch_regional_map fails assertion and impacts getting all features

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#257]
Expected to get a mask but it fails the assertion during at region,py line:411
```python
import siibra
v2 = siibra.get_region("julich", "v2")
v2.fetch_regional_map(siibra.spaces["bigbrain"], maptype="labelled")
```

This bug impacts feature fetching as well. With the following code, it is expected that all the features related to region v2 should be fetched. `match_location_to_regions` fail during `fetch_regional_map(siibra.spaces["bigbrain"], maptype="labelled")`
```python
import siibra
v2 = siibra.get_region("julich", "v2")
features = siibra.features.get(v2, siibra.features.Feature)
```

Note: this bug also blocks the addition of locations as feature concepts. (the rest is already implemented)

**Comment by dickscheid** [comment]
This is due to the still missing implementation of generating aggregated subtree masks when regional masks have different voxel spaces, as is the case for BigBrain masks.  

For the given use case of getting features, we can circumvent this in AnatomicalAnchor by testing the locations against region masks bottom up in a region subtree, instead of attempting to build the group mask at each parent node. We will push a fix.

The missing implementation of aggregated subtree masks in Region is still pending but not urgent. The assertion will be changed into a NotImplementedError with proper description by @AhmetNSimsek
