### ISSUE TITLE
[bug] some region mapped by big brain julich brain 2.9 cannot be found on parcellation

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#291]
region listed below:

```
MGBd (Metathalamus) left 
MGBd (Metathalamus) right 
MGBm (Metathalamus) left 
MGBm (Metathalamus) right 
MGBv (Metathalamus) left 
MGBv (Metathalamus) right 
CGL.lam1 (Metathalamus) left 
CGL.lam1 (Metathalamus) right 
CGL.lam2 (Metathalamus) left 
CGL.lam2 (Metathalamus) right 
CGL.lam3 (Metathalamus) left 
CGL.lam3 (Metathalamus) right 
CGL.lam4 (Metathalamus) left 
CGL.lam4 (Metathalamus) right 
CGL.lam5 (Metathalamus) left 
CGL.lam5 (Metathalamus) right 
CGL.lam6 (Metathalamus) left 
CGL.lam6 (Metathalamus) right 
```

are mapped in julich brain 2.9 in big brain, but does not appear on parcellation region hierarchy

This is a problem because

a/ there exist links in KG that point to viewer link
b/ since siibra-python do not recognise these regions exist in julich brain 2.9, they do not appear in region hierarchy, and no features will be shown

**Comment by SBludau** [comment]
I think this is due to the fact that some of the maps come from different sources.  All probability maps are based on 10 brains and are drawn in the OnlineSectionTracer and calculated by Hartmut. Hartmut generates his terminology file based on his database and the OnlineSectionTracer.

Special BigBrain mappings like the CGL lamina (e.g. CGL.lam1 (metathalamus) left) are calculated by Christian.

There must be a problem with the coordination and linking of the different datasets.

**Comment by AhmetNSimsek** [comment]
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/82 solves the issue

**Comment by AhmetNSimsek** [comment]
Solved with https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/42
