### ISSUE TITLE
feature.get BigBrainIntensityProfile is non deterministic

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#295]
as of 5ae4711de4966fbc1a6e7170ed919e8acf0c3a6e

code to reproduce

```python
import siibra
r = siibra.get_region("2.9", "hoc1")
with siibra.QUIET:
    name0 = siibra.features.get(r, "BigBrainIntensityProfile")[0].name
with siibra.QUIET:
    name1 = siibra.features.get(r, "BigBrainIntensityProfile")[0].name

assert name0 == name1 # assertion fails
```

**Comment by AhmetNSimsek** [comment]
Note: while the names/order are not deterministic, the values are:
```
import siibra
r = siibra.get_region("2.9", "hoc1")
with siibra.QUIET:
    fts0= siibra.features.get(r, "BigBrainIntensityProfile")
with siibra.QUIET:
    fts1 = siibra.features.get(r, "BigBrainIntensityProfile")
c0 = [f.anchor.location.coordinate for f in fts0]
c1 = [f.anchor.location.coordinate for f in fts1]
assert len(c0) == len(c1)
assert len([c for c in c0 if c not in c1])  == 0 and len([c for c in c1 if c not in c0]) == 0
```
This implies that `WagstylProfileLoader.match` returns profiles in non-deterministic order.

**Comment by AhmetNSimsek** [comment]
The source of the issue is found to be the method `feature.match` uses `set` to remove duplicate query results. `set` breaks the ordering. There are alternative solutions such as using a for loop or `dict.fromkeys()`. The former is quite slow. The former is much faster although not as fast as `set`.

["dicts are insertion ordered, dict.fromkeys doesn't lose ordering"](https://stackoverflow.com/a/17016257)
