### ISSUE TITLE
[bug] mni152 nii template returns None

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#386]
as of 5a649faf94f07abcd91c0c8979a58bcd07b9c7bf

code to reproduce:

```python
import siibra
space = siibra.spaces["mni152"]
assert space.get_template().fetch("nii") 
```

expected result, assert succeeds

actual behavior: assert fails (assert None)

prime cause: mni152 providers are `zip/nii` and `neuroglancer/precomputed`. Current implementation uses exact format match, as such `nii` does not match `zip/nii`

proposed solution: curate a dict of aliases. e.g. when user query nii, also queries zip/nii

**Comment by AhmetNSimsek** [comment]
I do not agree that this is a bug since `space.get_template().formats` does not list `nii` alone. But I agree that asking for `nii` should be able to call `zip/nii` as well.

I agree with the dictionary idea. We could also add `nifti` as another alias. This could be expanded for others later as well. (potentially we could expand 'image' and 'mesh' with this system as well)
