### ISSUE TITLE
Fetch volume metaset/datasets from parcellationmap

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-python#407]
A method that returns the metadata concerning volumes that can be fetched from a parcellationmap.Map object could be useful for API and also decrease the overhead when building a map object (`map.datasets = [*cls.extract_datasets(spec), *[ds for v in mp.volumes for ds in v.datasets]`).

**Comment by xgui3783** [comment]
for the record, `map.datasets = [*cls.extract_datasets(spec), *[ds for v in mp.volumes for ds in v.datasets]` is this not what the API is doing currently, and it would not be very useful (since the link metadata is lost)

I propose a `info` or `fetch_info` instance method, which takes the same input argument as `fetch`, but instead of returning a nifti image, or a mesh, returns the metadata associated with the volume (publications, doi, contributors, etc)

**Comment by AhmetNSimsek** [comment]
It was decided in a dev meeting in SEP 2024 that the maps should contain the corresponding datasets in their configurations. solved by https://github.com/FZJ-INM1-BDA/siibra-configurations/commit/b58e37a107c11291a211fd0f55c60044e550c0d2
