### ISSUE TITLE
Look of "CellDensityProfile" in Features

### ISSUE THREAD

**Issue by KimLothmann** [FZJ-INM1-BDA/siibra-python#475]
everything is mentioned in the picture. We can discuss the question regarding the coordinates in the next meeting and possibly change it afterwards. 

![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/131377539/22127dd2-b3dd-45e3-ab81-478cdce4b7ce)

**Comment by AhmetNSimsek** [comment]
The overlapping title issue is resolved. The coordinates in the title refer to the anchor. Changes in this title requires a change in the feature name which requires a refactoring that might cause the existing links to fail. This issue is already tracked separately (https://github.com/FZJ-INM1-BDA/siibra-python/issues/417).
