### ISSUE TITLE
Error when getting template for space

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-python#83]
Trying to get a template for a space throws a RuntimeError (see example below)

- Spaces tested: all spaces in siibra-python
- Version: latest develop version
- System: Windows

Example:
```
import siibra

template = siibra.spaces.BIG_BRAIN.get_template().fetch()
```

results in a RuntimeError:

```
RuntimeError: Could not resolve template image for Big Brain. This is most probably due to a misconfiguration of the volume src.
```

**Comment by dickscheid** [comment]
The same code works for me with V0.2a1. Can you please check wether you have an environment variable set, specifically SIIBRA_CONFIG_GITLAB_PROJECT_TAG? This would explain.

**Comment by dickscheid** [comment]
Another possible explanation: We are running a mirror of the predefined configurations, which is accessed if the main configuration repo is not reachable. Since v0.2 introduced breaking changes to the configurations, it is important that the mirror has the latest changes. I am adding @xgui3783 to this thread to check wether the mirroring of configurations is working.

**Comment by marcenko** [comment]
It was an Issue with the SIIBRA_CONFIG_GITLAB_PROJECT_TAG.
Not using any tag solved the issue and now the right siibra-configuration repo is used
